class CreatePropEnts < ActiveRecord::Migration[6.0]
  def change
    create_table :prop_ents do |t|
      t.integer :prop_id, comment: "Property Id"
      t.integer :prop_val_yr, comment: "Appraisal or Tax Year"
      t.integer :sup_num, comment: "Supplement Version Number - 0 = represents certified data, supplemental data otherwise"
      t.integer :owner_id, comment: "Owner Id"
      t.integer :entity_id, comment: "Entity Id"
      t.string :entity_cd, limit: 10, comment: "10 character code that will represent the entity"
      t.string :entity_name, limit: 50, comment: "Descriptive Name of Entity"
      t.string :entity_xref_id, limit: 20, comment: "Entity Local Xref Id Number"
      t.integer :assessed_val, comment: "Assessed Value"
      t.integer :taxable_val, comment: "Taxable Value"
      t.integer :ab_amt, comment: "Abatement Exemption Amount Granted by Entity"
      t.integer :en_amt, comment: "Energy Exemption Amount Granted by Entity"
      t.integer :fr_amt, comment: "Freeport Exemption Amount Granted by Entity"
      t.integer :ht_amt, comment: "Historical Exemption Amount Granted by Entity"
      t.integer :pro_amt, comment: "Prorated Exemption Amount Granted by Entity"
      t.integer :pc_amt, comment: "Pollution Control Exemption Amount Granted by Entity"
      t.integer :so_amt, comment: "Solar Exemption Amount Granted by Entity"
      t.integer :ex366_amt, comment: "EX366 Exemption Amount Granted by Entity
Properties under $500 minimum exemption"
      t.integer :hs_amt, comment: "Homestead Amount granted by entity"
      t.integer :ov65_amt, comment: "Over 65 Amount granted by entity"
      t.integer :dp_amt, comment: "Disability Exemption Amount granted by entity"
      t.integer :dv_amt, comment: "Disabled Veteran Amount granted by entity"
      t.integer :ex_amt, comment: "Total Exemption Amount granted by entity
(Needed for Prorated Total Exemption Accounts)"
      t.integer :ch_amt, comment: "Charitable Exemption Amount granted by entity"
      t.integer :market_value, comment: "Market Value"
      t.integer :appraised_value, comment: "Appraised Value"
      t.integer :hs_cap, comment: "HS Cap"
      t.integer :ag_late_loss, comment: "Late ag loss"
      t.integer :freeport_late_loss, comment: "Late Freeport Loss"
      t.integer :hs_state_amt, comment: "Homestead Exemption State Amount"
      t.integer :hs_local_amt, comment: "Homestead Exemption Local Amount"
      t.integer :land_hstd_val, comment: "Land Homestead Value"
      t.integer :land_non_hstd_val, comment: "Land Non Homestead Value"
      t.integer :imprv_hstd_val, comment: "Improvement Homestead Value"
      t.integer :imprv_non_hstd_val, comment: "Improvement Non Homestead Value"
      t.integer :ag_use_val, comment: "Agriculture Use Value"
      t.integer :ag_market_val, comment: "Agriculture Market Value"
      t.integer :tim_use_val, comment: "Timber Use Value"
      t.integer :tim_market_val, comment: "Timber Market Value"
      t.boolean :partial_entity, null: false, default: false, comment: "If T the property is not 100% within the entity."
      t.integer :freeze_yr, comment: "Freeze Year"
      t.integer :freeze_ceiling, comment: "Freeze Ceiling"
      t.boolean :freeze_transfer_flag, null: false, default: false, comment: "Freeze Transfer Flag"
      t.date :freeze_transfer_date, comment: "Freeze Transfer Date"
      t.integer :freeze_previous_tax, comment: "Freeze Previous Tax"
      t.integer :freeze_previous_tax_unfrozen, comment: "Freeze Previous Tax Unfrozen"
      t.decimal :freeze_transfer_percentage, precision: 9, scale: 6, comment: "Freeze Transfer Percentage"
      t.integer :lve_amt, comment: "Leased vehicle exemption amount"
      t.integer :eco_amt, comment: "ECO exemption amount"
      t.integer :ag_use_val_ne, comment: "Ag use val non-exempt"
      t.integer :ag_use_val_ex, comment: "Ag use val exempt"
      t.integer :ag_market_ne, comment: "Ag market non-exempt"
      t.integer :ag_market_ex, comment: "Ag market exempt"
      t.integer :timber_use_ne, comment: "Timber use non-exempt"
      t.integer :timber_use_ex, comment: "Timber use exempt"
      t.integer :timber_market_ne, comment: "Timber market non-exempt"
      t.integer :timber_market_ex, comment: "Timber market exempt"
      t.integer :new_val_hs, comment: "New Homesite Value"
      t.integer :new_val_nhs, comment: "New Non-Homesite Value"
      t.integer :new_val_p, comment: "New Personal Value"
      t.integer :new_val_taxable, comment: "New Taxable Value"
      t.integer :dataset_id, comment: "Unique number that identifies this export"
      t.integer :chodo_amt, comment: "CHODO Exemption Amount Granted by Entity"
      t.decimal :ent_pct_land_hs, precision: 15, scale: 10, comment: "Land Homesite Entity Percentage"
      t.decimal :ent_pct_land_nonhs, precision: 15, scale: 10, comment: "Land Non-Homesite Entity Percentage"
      t.decimal :ent_pct_imprv_hs, precision: 15, scale: 10, comment: "Improvement Homesite Entity Percentage"
      t.decimal :ent_pct_imprv_nonhs, precision: 15, scale: 10, comment: "Improvement Non-Homesite Entity Percentage"
      t.decimal :ent_pct_ag_use, precision: 15, scale: 10, comment: "Ag Use Entity Percentage"
      t.decimal :ent_pct_ag_mkt, precision: 15, scale: 10, comment: "Ag Market Entity Percentage"
      t.decimal :ent_pct_tim_use, precision: 15, scale: 10, comment: "Timber Use Entity Percentage"
      t.decimal :ent_pct_tim_mkt, precision: 15, scale: 10, comment: "Timber Market Entity Percentage"
      t.decimal :ent_pct_pers, precision: 15, scale: 10, comment: "Personal Property Entity Percentage"
      t.decimal :ent_pct_min, precision: 15, scale: 10, comment: "Mineral Property Entity Percentage"
      t.decimal :ent_pct_auto, precision: 15, scale: 10, comment: "Automotive Property Entity Percentage"
      t.integer :lih_amt, comment: "LIH Exemption Amount Granted by Entity"
      t.integer :git_amt, comment: "GIT Exemption Amount Granted by Entity"
      t.integer :dvhs_amt, comment: "Disabled Veteran Homestead Amount granted by entity"
      t.boolean :tax_increment_flag, null: false, default: false, comment: "Tax Increment Flag (T or F)"
      t.integer :tax_increment_imprv_val, comment: "Tax Increment Improvement Value"
      t.integer :tax_increment_land_val, comment: "Tax Increment Land Value"
      t.decimal :weed_taxable_acres, precision: 15, scale: 4, comment: "Weed Taxable Acres (4 Decimal Places)"
      t.decimal :hs_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for HS exemption"
      t.decimal :ov65_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for OV65 exemption"
      t.decimal :ov65s_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for OV65S exemption"
      t.decimal :dp_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DP exemption"
      t.decimal :dps_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DPS exemption"
      t.decimal :dv1_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV1 exemption"
      t.decimal :dv1s_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV1S exemption"
      t.decimal :dv2_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV2 exemption"
      t.decimal :dv2s_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV2S exemption"
      t.decimal :dv3_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV3 exemption"
      t.decimal :dv3s_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV3S exemption"
      t.decimal :dv4_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV4 exemption"
      t.decimal :dv4s_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DV4S exemption"
      t.decimal :dvhs_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DVHS exemption"
      t.decimal :ex_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for EX exemption"
      t.decimal :ab_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for AB exemption"
      t.decimal :en_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for EN exemption"
      t.decimal :fr_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for FR exemption"
      t.decimal :ht_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for HT exemption"
      t.decimal :pro_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for PRO exemption"
      t.decimal :pc_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for PC exemption"
      t.decimal :so_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for SO exemption"
      t.decimal :ex366_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for EX366 exemption"
      t.decimal :ch_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for CH exemption"
      t.decimal :eco_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for ECO exemption"
      t.decimal :chodo_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for CHODO exemption"
      t.decimal :lih_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for LIH exemption"
      t.decimal :git_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for GIT exemption"
      t.string :freeze_exmpt_type_cd, limit: 5, comment: "Freeze Exemption Type"
      t.string :freeze_transfer_exmpt_type_cd, limit: 5, comment: "Freeze Transfer Exemption Type"
      t.string :tax_increment_zone_cd, limit: 10, comment: "Tax Increment Zone Code"
      t.string :tax_increment_zone_desc, limit: 50, comment: "Tax Increment Zone Description"
      t.integer :omitted_imprv_hstd_val, comment: "Omitted Improvement Homestead Value by entity"
      t.integer :omitted_imprv_non_hstd_val, comment: "Omitted Improvement Non-Homestead Value by entity"
      t.integer :clt_amt, comment: "Community Land Trust Amount granted by entity"
      t.decimal :clt_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for CLT exemption"
      t.integer :dvhss_amt, comment: "DVHS Surviving Spouse Amount granted by entity"
      t.decimal :dvhss_allocation_factor, precision: 15, scale: 10, comment: "Allocation Factor for DVHS Surviving Spouse  exemption"
      t.decimal :homestead_group_exemption_factor, precision: 15, scale: 10, comment: "Homestead Group Exemption Factor (10 decimals)"
      t.integer :ex_xd_amt, comment: "EX-XD 11.181 Exemption Amount granted by entity"
      t.decimal :ex_xd_allocation_factor, precision: 15, scale: 10, comment: "EX-XD 11.181 exemption Allocation Factor"
      t.integer :ex_xf_amt, comment: "EX-XF 11.183 Exemption Amount granted by entity"
      t.decimal :ex_xf_allocation_factor, precision: 15, scale: 10, comment: "EX-XF 11.183 exemptionAllocation Factor"
      t.integer :ex_xg_amt, comment: "EX-XG 11.184 Exemption Amount granted by entity"
      t.decimal :ex_xg_allocation_factor, precision: 15, scale: 10, comment: "EX-XG 11.184 Exemption Allocation Factor"
      t.integer :ex_xh_amt, comment: "EX-XH 11.185 Exemption Amount granted by entity"
      t.decimal :ex_xh_allocation_factor, precision: 15, scale: 10, comment: "EX-XH 11.185 Exemption Allocation Factor"
      t.integer :ex_xi_amt, comment: "EX-XI 11.19 Exemption Amount granted by entity"
      t.decimal :ex_xi_allocation_factor, precision: 15, scale: 10, comment: "EX-XI 11.19 Exemption Allocation Factor"
      t.integer :ex_xj_amt, comment: "EX-XJ 11.21 Exemption Amount granted by entity"
      t.decimal :ex_xj_allocation_factor, precision: 15, scale: 10, comment: "EX-XJ 11.21 Exemption Allocation Factor"
      t.integer :ex_xl_amt, comment: "EX-XL 11.231 Exemption Amount granted by entity"
      t.decimal :ex_xl_allocation_factor, precision: 15, scale: 10, comment: "EX-XL 11.231 Exemption Allocation Factor"
      t.integer :ex_xm_amt, comment: "EX-XM 11.25 Exemption Amount granted by entity"
      t.decimal :ex_xm_allocation_factor, precision: 15, scale: 10, comment: "EX-XM 11.25 Exemption Allocation Factor"
      t.integer :ex_xn_amt, comment: "EX-XN 11.252 Exemption Amount granted by entity"
      t.decimal :ex_xn_allocation_factor, precision: 15, scale: 10, comment: "EX-XN 11.252 Exemption Allocation Factor"
      t.integer :ex_xo_amt, comment: "EX-XO 11.254 Exemption Amount granted by entity"
      t.decimal :ex_xo_allocation_factor, precision: 15, scale: 10, comment: "EX-XO 11.254 Exemption Allocation Factor"
      t.integer :ex_xp_amt, comment: "EX-XP 11.271 Exemption Amount granted by entity"
      t.decimal :ex_xp_allocation_factor, precision: 15, scale: 10, comment: "EX-XP 11.271 Exemption Allocation Factor"
      t.integer :ex_xq_amt, comment: "EX-XQ 11.29 Exemption Amount granted by entity"
      t.decimal :ex_xq_allocation_factor, precision: 15, scale: 10, comment: "EX-XQ 11.29 Exemption Allocation Factor"
      t.integer :ex_xr_amt, comment: "EX-XR 11.30 Exemption Amount granted by entity"
      t.decimal :ex_xr_allocation_factor, precision: 15, scale: 10, comment: "EX-XR 11.30 Exemption Allocation Factor"
      t.integer :ex_xs_amt, comment: "EX-XS 11.33 Exemption Amount granted by entity"
      t.decimal :ex_xs_allocation_factor, precision: 15, scale: 10, comment: "EX-XS 11.33 Exemption Allocation Factor"
      t.integer :ex_xt_amt, comment: "EX-XT 11.34 Exemption Amount granted by entity"
      t.decimal :ex_xt_allocation_factor, precision: 15, scale: 10, comment: "EX-XT 11.34 Exemption Allocation Factor"
      t.integer :ex_xu_amt, comment: "EX-XU 11.23 Exemption Amount granted by entity"
      t.decimal :ex_xu_allocation_factor, precision: 15, scale: 10, comment: "EX-XU 11.23 Exemption Allocation Factor"
      t.integer :ex_xv_amt, comment: "EX-XV Exemption Amount granted by entity"
      t.decimal :ex_xv_allocation_factor, precision: 15, scale: 10, comment: "EX-XV Exemption Allocation Factor"
      t.integer :ex_xa_amt, comment: "EX-XA Exemption Amount granted by entity"
      t.decimal :ex_xa_allocation_factor, precision: 15, scale: 10, comment: "EX-XA Exemption Allocation Factor"
      t.decimal :lve_allocation_factor, precision: 15, scale: 10, comment: "Leased vehicle exemption allocation factor"
      t.integer :ppv_amt, comment: "Personal Property vehicle exemption amount"
      t.decimal :ppv_allocation_factor, precision: 15, scale: 10, comment: "Personal Property vehicle exemption allocation factor"
      t.integer :dvch_amt, comment: "Disabled Veteran Charity Homestead exemption amount"
      t.decimal :dvch_allocation_factor, precision: 15, scale: 10, comment: "Disabled Veteran Charity Homestead exemption allocation factor"
      t.integer :dvchs_amt, comment: "Disabled Veteran Charity Homestead Spouse exemption amount"
      t.decimal :dvchs_allocation_factor, precision: 15, scale: 10, comment: "Disabled Veteran Charity Homestead Spouse exemption allocation factor"
      t.integer :masss_amt, comment: "Member Armed Services Surviving Spouse exemption amount"
      t.decimal :masss_allocation_factor, precision: 15, scale: 10, comment: "Member Armed Services Surviving Spouse exemption allocation factor"
      t.integer :pp_late_interstate_allocation_val, comment: "Property interstate allocation value that is subject to penalty by entity"
      t.integer :frss_amt, comment: "First Responder Surviving Spouse exemption amount"
      t.decimal :frss_allocation_factor, precision: 15, scale: 10, comment: "First Responder Surviving Spouse exemption allocation factor"
      t.integer :abmno_amt, comment: "ABMNO (Abatement-MNO) exemption amount"
      t.decimal :abmno_allocation_factor, precision: 15, scale: 10, comment: "ABMNO (Abatement-MNO) exemption allocation factor"
      t.integer :dis_amt, comment: "Disaster Damage Exemption amount"
      t.decimal :dis_allocation_factor, precision: 15, scale: 10, comment: "Disaster Damage Exemption allocation factor"

      t.timestamps
    end
  end
end
