class CreateProps < ActiveRecord::Migration[6.0]
  def change
    create_table :props do |t|
      t.integer :prop_id, comment: "Property ID"
      t.string :prop_type_cd, limit: 5, comment: "Property Type Code:
R = Real
P = Business Personal Property
M = Mobile Home
MN = Mineral
A = Automobiles"
      t.integer :prop_val_yr, comment: "Appraisal or Tax Year"
      t.integer :sup_num, comment: "Supplement Version Number - 0 = represents certified data, supplemental data otherwise"
      t.string :sup_action, limit: 2, comment: "Supplemental Action - If sup_num > 0, indicates the action to be taken on the property:
A - Add
M - Modify
D - Delete"
      t.string :sup_cd, limit: 10, comment: "Supplement Change Code - User defined"
      t.string :sup_desc, limit: 500, comment: "Supplement Change Description"
      t.string :geo_id, limit: 50, comment: "Geographic ID"
      t.integer :py_owner_id, comment: "Property Year Owner ID – PACS Internal ID"
      t.string :py_owner_name, limit: 70, comment: "Property Year Owner Name"
      t.boolean :partial_owner, null: false, default: false, comment: "Partial Owner (T or F)
This indicates if there are other owners for this property.  The additional owners will appear as separate records in this layout."
      t.integer :udi_group, comment: "This field indicates the UDI group that a partial owner is part of.  This is used to group multi owner properties."
      t.string :py_addr_line1, limit: 60, comment: "Property Year Owner Address Line 1"
      t.string :py_addr_line2, limit: 60, comment: "Property Year Owner Address Line 2"
      t.string :py_addr_line3, limit: 60, comment: "Property Year Owner Address Line 3"
      t.string :py_addr_city, limit: 50, comment: "Property Year Owner Address City"
      t.string :py_addr_state, limit: 50, comment: "Property Year Owner Address State"
      t.string :py_addr_country, limit: 5, comment: "Property Year Owner Address Country"
      t.string :py_addr_zip, limit: 5, comment: "Property Year Owner Address Zip (Zip Only)"
      t.string :py_addr_zip_cass, limit: 4, comment: "Property Year Owner Address Zip Cass (Cass Only)"
      t.string :py_addr_zip_rt, limit: 2, comment: "Property Year Owner Address Zip Route (Route Only)"
      t.boolean :py_confidential_flag, null: false, default: false, comment: "Property Year Owner Confidential Flag (T or F)"
      t.boolean :py_address_suppress_flag, null: false, default: false, comment: "Property Year Owner
Address Suppression Flag (T or F)"
      t.boolean :py_addr_ml_deliverable, null: false, default: false, comment: "Property Year Owner Address
Y = deliverable address
N = undeliverable address"
      t.string :situs_street_prefx, limit: 10, comment: "Situs/Location Street Prefix"
      t.string :situs_street, limit: 50, comment: "Situs/Location Street"
      t.string :situs_street_suffix, limit: 10, comment: "Situs/Location Street Suffix"
      t.string :situs_city, limit: 30, comment: "Situs/Location City"
      t.string :situs_zip, limit: 10, comment: "Situs/Location Zip"
      t.string :legal_desc, limit: 255, comment: "Legal Description"
      t.string :legal_desc2, limit: 255, comment: "Additional Legal Description"
      t.decimal :legal_acreage, precision: 16, scale: 4, comment: "Legal Acreage (4 Decimals)"
      t.string :abs_subdv_cd, limit: 10, comment: "Abstract/Subdivision code"
      t.string :hood_cd, limit: 10, comment: "Neighborhood code"
      t.string :block, limit: 50, comment: "Block"
      t.string :tract_or_lot, limit: 50, comment: "Tract/lot"
      t.integer :land_hstd_val, comment: "Land Homestead Value"
      t.integer :land_non_hstd_val, comment: "Land Non-Homestead Value"
      t.integer :imprv_hstd_val, comment: "Improvement Homestead Value"
      t.integer :imprv_non_hstd_val, comment: "Improvement Non-Homestead value"
      t.integer :ag_use_val, comment: "Agriculture Use Value"
      t.integer :ag_market, comment: "Agriculture Market Value"
      t.integer :timber_use, comment: "Timber Use Value"
      t.integer :timber_market, comment: "Timber Market Value"
      t.integer :appraised_val, comment: "Appraised Value"
      t.integer :ten_percent_cap, comment: "Ten Percent Homestead Cap Adjustment"
      t.integer :assessed_val, comment: "Assessed Value (Appraised - Cap)"
      t.boolean :arb_protest_flag, null: false, default: false, comment: "ARB Protest Flag; indicates if a protest has been filed on behalf of this property.  (T / F)"
      t.string :deed_book_id, limit: 20, comment: "Deed Book ID"
      t.string :deed_book_page, limit: 20, comment: "Deed Book Page"
      t.string :deed_dt, limit: 25, comment: "Deed Date"
      t.integer :mortgage_co_id, comment: "Mortgage Company ID"
      t.string :mortage_co_name, limit: 70, comment: "Name of Mortgage Company"
      t.string :mortgage_acct_id, limit: 50, comment: "Mortgage Loan Number"
      t.integer :jan1_owner_id, comment: "January 1 Owner ID"
      t.string :jan1_owner_name, limit: 70, comment: "January 1 Owner Name"
      t.string :jan1_addr_line1, limit: 60, comment: "January 1 Address Line 1"
      t.string :jan1_addr_line2, limit: 60, comment: "January 1 Address Line 2"
      t.string :jan1_addr_line3, limit: 60, comment: "January 1 Address Line 3"
      t.string :jan1_addr_city, limit: 50, comment: "January 1 Address City"
      t.string :jan1_addr_state, limit: 50, comment: "January 1 Address State"
      t.string :jan1_addr_country, limit: 5, comment: "January 1 Address Country"
      t.string :jan1_addr_zip, limit: 5, comment: "January 1 Address Zip  (Zip Only)"
      t.string :jan1_addr_zip_cass, limit: 4, comment: "January 1 Address Zip Cass (Cass Only)"
      t.string :jan1_addr_zip_rt, limit: 2, comment: "January 1 Address Zip  Route (Route Only)"
      t.boolean :jan1_confidential_flag, null: false, default: false, comment: "January 1 Owner Confidential Flag (T or F)"
      t.boolean :jan1_address_suppress_flag, null: false, default: false, comment: "January 1 Owner
Address Suppression Flag (T or F)"
      t.boolean :jan1_ml_deliverable, null: false, default: false, comment: "January 1 Owner Address
Y = deliverable address
N = undeliverable address"
      t.boolean :hs_exempt, null: false, default: false, comment: "Homestead Exemption    (‘T’ or ‘F’)
‘T’ indicates that the property has the exemption"
      t.boolean :ov65_exempt, null: false, default: false, comment: "Over 65 Exemption (‘T’ or ‘F’)"
      t.string :ov65_prorate_begin, limit: 25, comment: "date the exemption began – used for proration"
      t.string :ov65_prorate_end, limit: 25, comment: "date the exemption ended – used for proration"
      t.boolean :ov65s_exempt, null: false, default: false, comment: "Over 65 Surviving Spouse (‘T’ or ‘F’)"
      t.boolean :dp_exempt, null: false, default: false, comment: "Disabled Person (‘T’ or ‘F’)"
      t.boolean :dv1_exempt, null: false, default: false, comment: "Disabled Veteran - 10% to 30%  (‘T’ or ‘F’)"
      t.boolean :dv1s_exempt, null: false, default: false, comment: "Disabled Veteran - 10% to 30%  Surviving Spouse"
      t.boolean :dv2_exempt, null: false, default: false, comment: "Disabled Veteran - 31% to 50%  (‘T’ or ‘F’)"
      t.boolean :dv2s_exempt, null: false, default: false, comment: "Disabled Veteran - 31% to 50% Surviving Spouse"
      t.boolean :dv3_exempt, null: false, default: false, comment: "Disabled Veteran - 51% to 70% (T or F)"
      t.boolean :dv3s_exempt, null: false, default: false, comment: "Disabled Veteran - 51% to 70% Surviving Spouse"
      t.boolean :dv4_exempt, null: false, default: false, comment: "Disabled Veteran - 71% to 100%  (‘T’ or ‘F’)"
      t.boolean :dv4s_exempt, null: false, default: false, comment: "Disabled Veteran - 71% to 100% Surviving Spouse"
      t.boolean :ex_exempt, null: false, default: false, comment: "EX (Total Exemption) (‘T’ or ‘F’)"
      t.string :ex_prorate_begin, limit: 25, comment: "Date the exemption began – used for proration"
      t.string :ex_prorate_end, limit: 25, comment: "Date the exemption ended – used for proration"
      t.boolean :lve_exempt, null: false, default: false, comment: "Leased vehicle exemption"
      t.boolean :ab_exempt, null: false, default: false, comment: "Abatement (‘T’ or ‘F’)"
      t.boolean :en_exempt, null: false, default: false, comment: "Energy  Exemption (‘T’ or ‘F’)"
      t.boolean :fr_exempt, null: false, default: false, comment: "Freeport Exemption (‘T’ or ‘F’)"
      t.boolean :ht_exempt, null: false, default: false, comment: "Historical Exemption (‘T’ or ‘F’)"
      t.boolean :pro_exempt, null: false, default: false, comment: "Prorated Exemption (‘T’ or ‘F’)"
      t.boolean :pc_exempt, null: false, default: false, comment: "Pollution Control Exemption (‘T’ or ‘F’)"
      t.boolean :so_exempt, null: false, default: false, comment: "Solar Exemption (‘T’ or ‘F’)"
      t.boolean :ex366_exempt, null: false, default: false, comment: "Exemption for properties under $500 (T or F)"
      t.boolean :ch_exempt, null: false, default: false, comment: "Charitable Exemption (T or F)"
      t.string :imprv_state_cd, limit: 10, comment: "State Code that is on the improvements"
      t.string :land_state_cd, limit: 10, comment: "State Code that is on the land"
      t.string :personal_state_cd, limit: 10, comment: "State Code that is on the personal property"
      t.string :mineral_state_cd, limit: 10, comment: "State Code that is on the mineral"
      t.integer :land_acres, comment: "Sum of the acres based on land segments"
      t.integer :entity_agent_id, comment: "Agent for Entity Documents (I.E. Statements)
If id <> 0, then will contain information for the agent that is to receive entity documents"
      t.string :entity_agent_name, limit: 70, comment: "Entity Agent Name"
      t.string :entity_agent_addr_line1, limit: 60, comment: "Entity Agent Address Line 1"
      t.string :entity_agent_addr_line2, limit: 60, comment: "Entity Agent Address Line 2"
      t.string :entity_agent_addr_line3, limit: 60, comment: "Entity Agent Address Line 3"
      t.string :entity_agent_city, limit: 50, comment: "Entity Agent Address City"
      t.string :entity_agent_state, limit: 50, comment: "Entity Agent Address State"
      t.string :entity_agent_country, limit: 5, comment: "Entity Agent Address Country"
      t.string :entity_agent_zip, limit: 5, comment: "Entity Agent Address Zip (Zip Only)"
      t.string :entity_agent_cass, limit: 4, comment: "Entity Agent Address Zip Cass (Cass Only)"
      t.string :entity_agent_rt, limit: 2, comment: "Entity Agent Address Zip Route (Route Only)"
      t.integer :ca_agent_id, comment: "Agent for Chief Appraiser Documents (I.E. Appraisal Notice)
If id <> 0, then will contain information for the agent that is to receive chief appraiser documents"
      t.string :ca_agent_name, limit: 70, comment: "Chief Appraiser Agent Name"
      t.string :ca_agent_addr_line1, limit: 60, comment: "Chief Appraiser Address Line 1"
      t.string :ca_agent_addr_line2, limit: 60, comment: "Chief Appraiser Address Line 2"
      t.string :ca_agent_addr_line3, limit: 60, comment: "Chief Appraiser Address Line 3"
      t.string :ca_agent_city, limit: 50, comment: "Chief Appraiser Address City"
      t.string :ca_agent_state, limit: 50, comment: "Chief Appraiser Address State"
      t.string :ca_agent_country, limit: 5, comment: "Chief Appraiser Address Country"
      t.string :ca_agent_zip, limit: 5, comment: "Chief Appraiser Address Zip (Zip Only)"
      t.string :ca_agent_zip_cass, limit: 4, comment: "Chief Appraiser Address Zip Cass (Cass Only)"
      t.string :ca_agent_zip_rt, limit: 2, comment: "Chief Appraiser Address Zip Route (Route Only)"
      t.integer :arb_agent_id, comment: "Agent for ARB Documents (I.E. ARB Notice)
If id <> 0, then will contain information for the agent that is to receive arb documents"
      t.string :arb_agent_name, limit: 70, comment: "ARB Agent Name"
      t.string :arb_agent_addr_line1, limit: 60, comment: "ARB Agent Line 1"
      t.string :arb_agent_addr_line2, limit: 60, comment: "ARB Agent Line 2"
      t.string :arb_agent_addr_line3, limit: 60, comment: "ARB Agent Line 3"
      t.string :arb_agent_city, limit: 50, comment: "ARB Agent City"
      t.string :arb_agent_state, limit: 50, comment: "ARB Agent State"
      t.string :arb_agent_country, limit: 5, comment: "ARB Agent County"
      t.string :arb_agent_zip, limit: 5, comment: "ARB Agent Zip (Zip Only)"
      t.string :arb_agent_zip_cass, limit: 4, comment: "ARB Agent Zip Cass (Cass Only)"
      t.string :arb_agent_zip_rt, limit: 2, comment: "ARB Agent Zip Route (Route Only)"
      t.string :mineral_type_of_int, limit: 5, comment: "Mineral Interest Type"
      t.decimal :mineral_int_pct, precision: 15, scale: 10, comment: "Mineral Interest Percent (10 Decimals)"
      t.string :productivity_use_code, limit: 3, comment: "Productivity Use Code"
      t.integer :timber_78_market, comment: "1978 timber market value"
      t.integer :ag_late_loss, comment: "Late ag loss"
      t.integer :late_freeport_penalty, comment: "Late freeport penalty"
      t.string :dba, limit: 40, comment: "Doing business as"
      t.integer :market_value, comment: "Property market value"
      t.date :ov65_deferral_date, comment: "OV65 Deferral Date"
      t.date :dp_deferral_date, comment: "DP Deferral Date"
      t.string :ref_id1, limit: 25, comment: "Property Reference ID 1"
      t.string :ref_id2, limit: 25, comment: "Property Reference ID 2"
      t.string :situs_num, limit: 15, comment: "Situs Number"
      t.string :situs_unit, limit: 5, comment: "Situs Unit #"
      t.integer :appr_owner_id, comment: "Current Appraisal Owner ID"
      t.string :appr_owner_name, limit: 70, comment: "Current Appraisal Owner Name"
      t.string :appr_addr_line1, limit: 60, comment: "Current Appraisal Address Line 1"
      t.string :appr_addr_line2, limit: 60, comment: "Current Appraisal Address Line 2"
      t.string :appr_addr_line3, limit: 60, comment: "Current Appraisal Address Line 3"
      t.string :appr_addr_city, limit: 50, comment: "Current Appraisal Address City"
      t.string :appr_addr_state, limit: 50, comment: "Current Appraisal Address State"
      t.string :appr_addr_country, limit: 5, comment: "Current Appraisal Address Country"
      t.string :appr_addr_zip, limit: 5, comment: "Current Appraisal Address Zip (Zip Only)"
      t.string :appr_addr_zip_cass, limit: 4, comment: "Current Appraisal Address Zip Cass (Cass Only)"
      t.string :appr_addr_zip_cass_route, limit: 2, comment: "Current Appraisal Address Zip Rt (Route Only)"
      t.boolean :appr_ml_deliverable, null: false, default: false, comment: "Current Appraisal Owner Address
Y = deliverable address
N = undeliverable address"
      t.boolean :appr_confidential_flag, null: false, default: false, comment: "Current Appraisal Owner
Confidential Flag (T or F)"
      t.boolean :appr_address_suppress_flag, null: false, default: false, comment: "Current Appraisal Owner
Address Suppression Flag (T or F)"
      t.string :appr_confidential_name, limit: 70, comment: "Current Appraisal Owner Confidential Name"
      t.string :py_confidential_name, limit: 70, comment: "Property Year Owner Confidential Name"
      t.string :jan1_confidential_name, limit: 70, comment: "Jan 1 Owner Confidential Name"
      t.boolean :rendition_filed, null: false, default: false, comment: "Rendition Filed (T or F)"
      t.date :rendition_date, comment: "Rendition Filed Date"
      t.integer :rendition_penalty, comment: "If > 0, indicates that a Rendition Penalty should be calculated."
      t.date :rendition_penalty_date_paid, comment: "Rendition 10% Penalty Date Paid"
      t.integer :rendition_fraud_penalty, comment: "Rendition Fraud Penalty"
      t.date :rendition_fraud_penalty_date_paid, comment: "Rendition Fraud Penalty Date Paid"
      t.string :entities, limit: 140, comment: "Entities list"
      t.boolean :eco_exempt, null: false, default: false, comment: "eco exemption"
      t.integer :dataset_id, comment: "Unique number that identifies this export"
      t.string :deed_num, limit: 50, comment: "Deed Number"
      t.boolean :chodo_exempt, null: false, default: false, comment: "Exemption for charitable organizations providing low-income housing (T or F)"
      t.boolean :local_option_pct_only_flag_hs, null: false, default: false, comment: "Local option flag for Homesite Percentage (T or F)"
      t.boolean :local_option_pct_only_flag_ov65, null: false, default: false, comment: "Local option flag for OV65 exemption (T or F)"
      t.boolean :local_option_pct_only_flag_ov65s, null: false, default: false, comment: "Local option flag for OV65S exemption (T or F)"
      t.boolean :local_option_pct_only_flag_dp, null: false, default: false, comment: "Local option flag for DP exemption (T or F)"
      t.boolean :freeze_only_flag_ov65, null: false, default: false, comment: "Freeze only flag for OV65 exemption (T or F)"
      t.boolean :freeze_only_flag_ov65s, null: false, default: false, comment: "Freeze only flag for OV65S exemption (T or F)"
      t.boolean :freeze_only_flag_dp, null: false, default: false, comment: "Freeze only flag for DP exemption (T or F)"
      t.boolean :apply_percent_exemption_flag, null: false, default: false, comment: "Apply percent exemption flag (T or F)"
      t.string :exemption_percentage, limit: 15, comment: "Exemption percentage (string representing a floating point number)"
      t.boolean :vit_flag, null: false, default: false, comment: "VIT flag; T if property is VIT, otherwise F"
      t.boolean :lih_exempt, null: false, default: false, comment: "Exemption for charitable organizations providing low-income housing with volunteer labor (T or F)"
      t.boolean :git_exempt, null: false, default: false, comment: "Goods in Transit Exemption (‘T’ or ‘F’)"
      t.boolean :dps_exempt, null: false, default: false, comment: "Disabled Person - Surviving Spouse (‘T’ or ‘F’)"
      t.date :dps_deferral_date, comment: "DPS Deferral Date"
      t.boolean :local_option_pct_only_flag_dps, null: false, default: false, comment: "Local option flag for DPS exemption (T or F)"
      t.boolean :freeze_only_flag_dps, null: false, default: false, comment: "Freeze only flag for DPS exemption (T or F)"
      t.boolean :dvhs_exempt, null: false, default: false, comment: "Disabled Veteran Homestead - 100% (T or F)"
      t.integer :hs_qualify_yr, comment: "Qualify Year for HS exemption"
      t.integer :ov65_qualify_yr, comment: "Qualify Year for OV65 exemption"
      t.integer :ov65s_qualify_yr, comment: "Qualify Year for OV65S exemption"
      t.integer :dp_qualify_yr, comment: "Qualify Year for DP exemption"
      t.integer :dps_qualify_yr, comment: "Qualify Year for DPS exemption"
      t.integer :dv1_qualify_yr, comment: "Qualify Year for DV1 exemption"
      t.integer :dv1s_qualify_yr, comment: "Qualify Year for DV1S exemption"
      t.integer :dv2_qualify_yr, comment: "Qualify Year for DV2 exemption"
      t.integer :dv2s_qualify_yr, comment: "Qualify Year for DV2S exemption"
      t.integer :dv3_qualify_yr, comment: "Qualify Year for DV3 exemption"
      t.integer :dv3s_qualify_yr, comment: "Qualify Year for DV3S exemption"
      t.integer :dv4_qualify_yr, comment: "Qualify Year for DV4 exemption"
      t.integer :dv4s_qualify_yr, comment: "Qualify Year for DV4S exemption"
      t.integer :dvhs_qualify_yr, comment: "Qualify Year for DVHS exemption"
      t.integer :ex_qualify_yr, comment: "Qualify Year for EX exemption"
      t.integer :ab_qualify_yr, comment: "Qualify Year for AB exemption"
      t.integer :en_qualify_yr, comment: "Qualify Year for EN exemption"
      t.integer :fr_qualify_yr, comment: "Qualify Year for FR exemption"
      t.integer :ht_qualify_yr, comment: "Qualify Year for HT exemption"
      t.integer :pro_qualify_yr, comment: "Qualify Year for PRO exemption"
      t.integer :pc_qualify_yr, comment: "Qualify Year for PC exemption"
      t.integer :so_qualify_yr, comment: "Qualify Year for SO exemption"
      t.integer :ex366_qualify_yr, comment: "Qualify Year for EX366 exemption"
      t.integer :ch_qualify_yr, comment: "Qualify Year for CH exemption"
      t.integer :eco_qualify_yr, comment: "Qualify Year for ECO exemption"
      t.integer :chodo_qualify_yr, comment: "Qualify Year for CHODO exemption"
      t.integer :lih_qualify_yr, comment: "Qualify Year for LIH exemption"
      t.integer :git_qualify_yr, comment: "Qualify Year for GIT exemption"
      t.string :mortgage_addr_line1, limit: 60, comment: "Mortgage Company Address Line 1"
      t.string :mortgage_addr_line2, limit: 60, comment: "Mortgage Company Address Line 2"
      t.string :mortgage_addr_line3, limit: 60, comment: "Mortgage Company Address Line 3"
      t.string :mortgage_addr_city, limit: 50, comment: "Mortgage Company Address City"
      t.string :mortgage_addr_state, limit: 50, comment: "Mortgage Company Address State"
      t.string :mortgage_addr_country, limit: 5, comment: "Mortgage Company Address Country"
      t.string :mortgage_addr_zip, limit: 5, comment: "Mortgage Company Address Zip (Zip Only)"
      t.string :mortgage_addr_zip_cass, limit: 4, comment: "Mortgage Company Address Zip Cass (Cass Only)"
      t.string :mortgage_addr_zip_rt, limit: 2, comment: "Mortgage Company Address Zip Route (Route Only)"
      t.boolean :mortgage_addr_ml_deliverable, null: false, default: false, comment: "Mortgage Company Address
Y = deliverable address
N = undeliverable address"
      t.string :sic_code, limit: 10, comment: "SIC Code (new position in file due to change in length from 5 to 10)"
      t.boolean :omitted_property_flag, null: false, default: false, comment: "Omitted Property
Y = Omitted
N = Not omitted"
      t.string :hs_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :hs_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :ov65s_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :ov65s_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dp_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dp_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv1_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv1_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv1s_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv1s_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv2_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv2_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv2s_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv2s_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv3_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv3_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv3s_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv3s_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv4_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv4_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dv4s_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dv4s_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :lve_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :lve_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :ab_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :ab_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :en_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :en_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :fr_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :fr_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :ht_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :ht_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :pro_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :pro_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :pc_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :pc_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :so_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :so_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :ex366_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :ex366_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :ch_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :ch_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :dps_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :dps_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :eco_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :eco_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :chodo_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :chodo_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :lih_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :lih_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.string :git_prorate_begin, limit: 25, comment: "date the exemption began - used for proration"
      t.string :git_prorate_end, limit: 25, comment: "date the exemption ended - used for proration"
      t.boolean :clt_exempt, null: false, default: false, comment: "Exemption for community land trust (T or F)"
      t.string :clt_prorate_begin, limit: 25, comment: "date the exemption began – used for proration"
      t.string :clt_prorate_end, limit: 25, comment: "date the exemption ended – used for proration"
      t.integer :clt_qualify_yr, comment: "Qualify Year for CLT exemption"
      t.boolean :dvhss_exempt, null: false, default: false, comment: "Exemption for DVHS Surviving Spouse (T or F)"
      t.string :dvhss_prorate_begin, limit: 25, comment: "date the exemption began – used for proration"
      t.string :dvhss_prorate_end, limit: 25, comment: "date the exemption ended – used for proration"
      t.integer :dvhss_qualify_yr, comment: "Qualify Year for DVHS Surviving Spouse exemption"
      t.integer :omitted_imprv_hstd_val, comment: "Omitted Improvement Homestead Value"
      t.integer :omitted_imprv_non_hstd_val, comment: "Omitted Improvement Non-Homestead Value"
      t.string :dvhs_prorate_begin, limit: 25, comment: "date the exemption began – used for proration"
      t.string :dvhs_prorate_end, limit: 25, comment: "date the exemption ended – used for proration"
      t.boolean :ex_xd_exempt, null: false, default: false, comment: "EX-XD 11.181 exemption (‘T’ or ‘F’)"
      t.integer :ex_xd_qualify_yr, comment: "Qualify Year for EX-XD 11.181 exemption"
      t.string :ex_xd_prorate_begin, limit: 25, comment: "Proration begin date for EX-XD 11.181 exemption"
      t.string :ex_xd_prorate_end, limit: 25, comment: "Proration end date for EX-XD 11.181 exemption"
      t.boolean :ex_xf_exempt, null: false, default: false, comment: "EX-XF 11.183 exemption (‘T’ or ‘F’)"
      t.integer :ex_xf_qualify_yr, comment: "Qualify Year for EX-XF 11.183 exemption"
      t.string :ex_xf_prorate_begin, limit: 25, comment: "Proration begin date for EX-XF 11.183 exemption"
      t.string :ex_xf_prorate_end, limit: 25, comment: "Proration end date for EX-XF 11.183 exemption"
      t.boolean :ex_xg_exempt, null: false, default: false, comment: "EX-XG 11.184 exemption (‘T’ or ‘F’)"
      t.integer :ex_xg_qualify_yr, comment: "Qualify Year for EX-XG 11.184 exemption"
      t.string :ex_xg_prorate_begin, limit: 25, comment: "Proration begin date for EX-XG 11.184 exemption"
      t.string :ex_xg_prorate_end, limit: 25, comment: "Proration end date for EX-XG 11.184 exemption"
      t.boolean :ex_xh_exempt, null: false, default: false, comment: "EX-XH 11.185 exemption (‘T’ or ‘F’)"
      t.integer :ex_xh_qualify_yr, comment: "Qualify Year for EX-XH 11.185 exemption"
      t.string :ex_xh_prorate_begin, limit: 25, comment: "Proration begin date for EX-XH 11.185 exemption"
      t.string :ex_xh_prorate_end, limit: 25, comment: "Proration end date for EX-XH 11.185 exemption"
      t.boolean :ex_xi_exempt, null: false, default: false, comment: "EX-XI 11.19 exemption (‘T’ or ‘F’)"
      t.integer :ex_xi_qualify_yr, comment: "Qualify Year forEX-XI 11.19 exemption"
      t.string :ex_xi_prorate_begin, limit: 25, comment: "Proration begin date for EX-XI 11.19 exemption"
      t.string :ex_xi_prorate_end, limit: 25, comment: "Proration end date for EX-XI 11.19 exemption"
      t.boolean :ex_xj_exempt, null: false, default: false, comment: "EX-XJ 11.21 exemption (‘T’ or ‘F’)"
      t.integer :ex_xj_qualify_yr, comment: "Qualify Year for EX-XJ 11.21 exemption"
      t.string :ex_xj_prorate_begin, limit: 25, comment: "Proration begin date for EX-XJ 11.21 exemption"
      t.string :ex_xj_prorate_end, limit: 25, comment: "Proration end date for EX-XJ 11.21 exemption"
      t.boolean :ex_xl_exempt, null: false, default: false, comment: "EX-XL 11.231 exemption (‘T’ or ‘F’)"
      t.integer :ex_xl_qualify_yr, comment: "Qualify Year for EX-XL 11.231 exemption"
      t.string :ex_xl_prorate_begin, limit: 25, comment: "Proration begin date for EX-XL 11.231 exemption"
      t.string :ex_xl_prorate_end, limit: 25, comment: "Proration end date for EX-XL 11.231 exemption"
      t.boolean :ex_xm_exempt, null: false, default: false, comment: "EX-XM 11.25 exemption (‘T’ or ‘F’)"
      t.integer :ex_xm_qualify_yr, comment: "Qualify Year for EX-XM 11.25 exemption"
      t.string :ex_xm_prorate_begin, limit: 25, comment: "Proration begin date for EX-XM 11.25 exemption"
      t.string :ex_xm_prorate_end, limit: 25, comment: "Proration end date for EX-XM 11.25 exemption"
      t.boolean :ex_xn_exempt, null: false, default: false, comment: "EX-XN 11.252 exemption (‘T’ or ‘F’)"
      t.integer :ex_xn_qualify_yr, comment: "Qualify Year for EX-XN 11.252 exemption"
      t.string :ex_xn_prorate_begin, limit: 25, comment: "Proration begin date for EX-XN 11.252 exemption"
      t.string :ex_xn_prorate_end, limit: 25, comment: "Proration end date for EX-XN 11.252 exemption"
      t.boolean :ex_xo_exempt, null: false, default: false, comment: "EX-XO 11.254 exemption (‘T’ or ‘F’)"
      t.integer :ex_xo_qualify_yr, comment: "Qualify Year for EX-XO 11.254 exemption"
      t.string :ex_xo_prorate_begin, limit: 25, comment: "Proration begin date for EX-XO 11.254 exemption"
      t.string :ex_xo_prorate_end, limit: 25, comment: "Proration end date for EX-XO 11.254 exemption"
      t.boolean :ex_xp_exempt, null: false, default: false, comment: "EX-XP 11.271 exemption (‘T’ or ‘F’)"
      t.integer :ex_xp_qualify_yr, comment: "Qualify Year for EX-XP 11.271 exemption"
      t.string :ex_xp_prorate_begin, limit: 25, comment: "Proration begin date for EX-XP 11.271 exemption"
      t.string :ex_xp_prorate_end, limit: 25, comment: "Proration end date for EX-XP 11.271 exemption"
      t.boolean :ex_xq_exempt, null: false, default: false, comment: "EX-XQ 11.29 exemption (‘T’ or ‘F’)"
      t.integer :ex_xq_qualify_yr, comment: "Qualify Year for EX-XQ 11.29 exemption"
      t.string :ex_xq_prorate_begin, limit: 25, comment: "Proration begin date for EX-XQ 11.29 exemption"
      t.string :ex_xq_prorate_end, limit: 25, comment: "Proration end date for EX-XQ exemption 11.29 exemption"
      t.boolean :ex_xr_exempt, null: false, default: false, comment: "EX-XR 11.30 exemption (‘T’ or ‘F’)"
      t.integer :ex_xr_qualify_yr, comment: "Qualify Year for EX-XR 11.30 exemption"
      t.string :ex_xr_prorate_begin, limit: 25, comment: "Proration begin date for EX-XR 11.30 exemption"
      t.string :ex_xr_prorate_end, limit: 25, comment: "Proration end date for EX-XR 11.30 exemption"
      t.boolean :ex_xs_exempt, null: false, default: false, comment: "EX-XS 11.33 exemption (‘T’ or ‘F’)"
      t.integer :ex_xs_qualify_yr, comment: "Qualify Year for EX-XS 11.33 exemption"
      t.string :ex_xs_prorate_begin, limit: 25, comment: "Proration begin date for EX-XS 11.33 exemption"
      t.string :ex_xs_prorate_end, limit: 25, comment: "Proration end date for EX-XS 11.33 exemption"
      t.boolean :ex_xt_exempt, null: false, default: false, comment: "EX-XT 11.34 exemption (‘T’ or ‘F’)"
      t.integer :ex_xt_qualify_yr, comment: "Qualify Year for EX-XT 11.34 exemption"
      t.string :ex_xt_prorate_begin, limit: 25, comment: "Proration begin date for EX-XT 11.34 exemption"
      t.string :ex_xt_prorate_end, limit: 25, comment: "Proration end date for EX-XT 11.34 exemption"
      t.boolean :ex_xu_exempt, null: false, default: false, comment: "EX-XU 11.23 exemption (‘T’ or ‘F’)"
      t.integer :ex_xu_qualify_yr, comment: "Qualify Year for EX-XU 11.23 exemption"
      t.string :ex_xu_prorate_begin, limit: 25, comment: "Proration begin date for EX-XU 11.23 exemption"
      t.string :ex_xu_prorate_end, limit: 25, comment: "Proration end date for EX-XU 11.23 exemption"
      t.boolean :ex_xv_exempt, null: false, default: false, comment: "EX-XV  exemption (‘T’ or ‘F’)"
      t.integer :ex_xv_qualify_yr, comment: "Qualify Year for EX-XV exemption"
      t.string :ex_xv_prorate_begin, limit: 25, comment: "Proration begin date for EX-XV exemption"
      t.string :ex_xv_prorate_end, limit: 25, comment: "Proration end date for EX-XV exemption"
      t.boolean :ex_xa_exempt, null: false, default: false, comment: "EX-XA  exemption (‘T’ or ‘F’)"
      t.integer :ex_xa_qualify_yr, comment: "Qualify Year for EX-XA exemption"
      t.string :ex_xa_prorate_begin, limit: 25, comment: "Proration begin date for EX-XA exemption"
      t.string :ex_xa_prorate_end, limit: 25, comment: "Proration end date for EX-XA exemption"
      t.integer :lve_qualify_yr, comment: "Qualify Year for LVE exemption"
      t.boolean :ppv_exempt, null: false, default: false, comment: "Personal Property Vehicle exemption"
      t.integer :ppv_qualify_yr, comment: "Qualify Year for PPV exemption"
      t.string :ppv_prorate_begin, limit: 25, comment: "date PPV exemption began - used for proration"
      t.string :ppv_prorate_end, limit: 25, comment: "date PPV exemption ended - used for proration"
      t.boolean :dvch_exempt, null: false, default: false, comment: "Disabled Veteran Charity Homestead"
      t.integer :dvch_qualify_yr, comment: "Qualify Year for DVCH exemption"
      t.string :dvch_prorate_begin, limit: 25, comment: "date DVCH exemption began - used for proration"
      t.string :dvch_prorate_end, limit: 25, comment: "date DVCH exemption ended - used for proration"
      t.boolean :dvchs_exempt, null: false, default: false, comment: "Disabled Veteran Charity Homestead Spouse"
      t.integer :dvchs_qualify_yr, comment: "Qualify Year for DVCHS exemption"
      t.string :dvchs_prorate_begin, limit: 25, comment: "date DVCHS exemption began - used for proration"
      t.string :dvchs_prorate_end, limit: 25, comment: "date DVCHS exemption ended - used for proration"
      t.boolean :masss_exempt, null: false, default: false, comment: "Member Armed Services Surviving Spouse"
      t.integer :masss_qualify_yr, comment: "Qualify Year for MASSS exemption"
      t.string :masss_prorate_begin, limit: 25, comment: "date MASSS exemption began - used for proration"
      t.string :masss_prorate_end, limit: 25, comment: "date MASSS exemption ended - used for proration"
      t.integer :pp_late_interstate_allocation_val, comment: "Personal Property interstate allocation value that is subject to penalty"
      t.integer :appraised_val_reflecting_productivity_loss, comment: "Appraised Value reflecting Productivity Loss"
      t.integer :assessed_val_reflecting_productivity_loss, comment: "Assessed Value reflecting Productivity Loss"
      t.boolean :frss_exempt, null: false, default: false, comment: "First Responder Surviving Spouse"
      t.integer :frss_qualify_yr, comment: "Qualify Year for FRSS exemption"
      t.string :frss_prorate_begin, limit: 25, comment: "date FRSS exemption began - used for proration"
      t.string :frss_prorate_end, limit: 25, comment: "date FRSS exemption ended - used for proration"
      t.boolean :abmno_exempt, null: false, default: false, comment: "ABMNO (Abatement-MNO) exemption"
      t.integer :abmno_qualify_yr, comment: "Qualify Year for ABMNO exemption"
      t.string :abmno_prorate_begin, limit: 25, comment: "date ABMNO exemption began - used for proration"
      t.string :abmno_prorate_end, limit: 25, comment: "date ABMNO exemption ended - used for proration"
      t.date :dv1_deferral_date, comment: "DV1 exemption deferral date"
      t.date :dv2_deferral_date, comment: "DV2 exemption deferral date"
      t.date :dv3_deferral_date, comment: "DV3 exemption deferral date"
      t.date :dv4_deferral_date, comment: "DV4 exemption deferral date"
      t.date :dv1s_deferral_date, comment: "DV1S exemption deferral date"
      t.date :dv2s_deferral_date, comment: "DV2S exemption deferral date"
      t.date :dv3s_deferral_date, comment: "DV3S exemption deferral date"
      t.date :dv4s_deferral_date, comment: "DV4S exemption deferral date"
      t.boolean :dis_exempt, null: false, default: false, comment: "Disaster Damage Exemption"
      t.integer :dis_qualify_yr, comment: "Qualify Year for DIS exemption"
      t.string :dis_prorate_begin, limit: 25, comment: "Date DIS exemption began - used for proration"
      t.string :dis_prorate_end, limit: 25, comment: "Date DIS exemption ended - used for proration"

      t.timestamps
    end
  end
end
