class CreatePropEnts < ActiveRecord::Migration[6.0]
  def change
    create_table :prop_ents do |t|
      t.integer :prop_id
      t.integer :prop_val_yr
      t.integer :sup_num
      t.integer :owner_id
      t.integer :entity_id
      t.string :entity_cd, limit: 10
      t.string :entity_name, limit: 50
      t.string :entity_xref_id, limit: 20
      t.integer :assessed_val
      t.integer :taxable_val
      t.integer :ab_amt
      t.integer :en_amt
      t.integer :fr_amt
      t.integer :ht_amt
      t.integer :pro_amt
      t.integer :pc_amt
      t.integer :so_amt
      t.integer :ex366_amt
      t.integer :hs_amt
      t.integer :ov65_amt
      t.integer :dp_amt
      t.integer :dv_amt
      t.integer :ex_amt
      t.integer :ch_amt
      t.integer :market_value
      t.integer :appraised_value
      t.integer :hs_cap
      t.integer :ag_late_loss
      t.integer :freeport_late_loss
      t.integer :hs_state_amt
      t.integer :hs_local_amt
      t.integer :land_hstd_val
      t.integer :land_non_hstd_val
      t.integer :imprv_hstd_val
      t.integer :imprv_non_hstd_val
      t.integer :ag_use_val
      t.integer :ag_market_val
      t.integer :tim_use_val
      t.integer :tim_market_val
      t.string :partial_entity, limit: 1
      t.integer :freeze_yr
      t.integer :freeze_ceiling
      t.string :freeze_transfer_flag, limit: 1
      t.date :freeze_transfer_date
      t.integer :freeze_previous_tax
      t.integer :freeze_previous_tax_unfrozen
      t.integer :freeze_transfer_percentage
      t.integer :lve_amt
      t.integer :eco_amt
      t.integer :ag_use_val_ne
      t.integer :ag_use_val_ex
      t.integer :ag_market_ne
      t.integer :ag_market_ex
      t.integer :timber_use_ne
      t.integer :timber_use_ex
      t.integer :timber_market_ne
      t.integer :timber_market_ex
      t.integer :new_val_hs
      t.integer :new_val_nhs
      t.integer :new_val_p
      t.integer :new_val_taxable
      t.integer :dataset_id
      t.integer :chodo_amt
      t.integer :ent_pct_land_hs
      t.integer :ent_pct_land_nonhs
      t.integer :ent_pct_imprv_hs
      t.integer :ent_pct_imprv_nonhs
      t.integer :ent_pct_ag_use
      t.integer :ent_pct_ag_mkt
      t.integer :ent_pct_tim_use
      t.integer :ent_pct_tim_mkt
      t.integer :ent_pct_pers
      t.integer :ent_pct_min
      t.integer :ent_pct_auto
      t.integer :lih_amt
      t.integer :git_amt
      t.integer :dvhs_amt
      t.string :tax_increment_flag, limit: 1
      t.integer :tax_increment_imprv_val
      t.integer :tax_increment_land_val
      t.integer :weed_taxable_acres
      t.integer :hs_allocation_factor
      t.integer :ov65_allocation_factor
      t.integer :ov65s_allocation_factor
      t.integer :dp_allocation_factor
      t.integer :dps_allocation_factor
      t.integer :dv1_allocation_factor
      t.integer :dv1s_allocation_factor
      t.integer :dv2_allocation_factor
      t.integer :dv2s_allocation_factor
      t.integer :dv3_allocation_factor
      t.integer :dv3s_allocation_factor
      t.integer :dv4_allocation_factor
      t.integer :dv4s_allocation_factor
      t.integer :dvhs_allocation_factor
      t.integer :ex_allocation_factor
      t.integer :ab_allocation_factor
      t.integer :en_allocation_factor
      t.integer :fr_allocation_factor
      t.integer :ht_allocation_factor
      t.integer :pro_allocation_factor
      t.integer :pc_allocation_factor
      t.integer :so_allocation_factor
      t.integer :ex366_allocation_factor
      t.integer :ch_allocation_factor
      t.integer :eco_allocation_factor
      t.integer :chodo_allocation_factor
      t.integer :lih_allocation_factor
      t.integer :git_allocation_factor
      t.string :freeze_exmpt_type_cd, limit: 5
      t.string :freeze_transfer_exmpt_type_cd, limit: 5
      t.string :tax_increment_zone_cd, limit: 10
      t.string :tax_increment_zone_desc, limit: 50
      t.integer :omitted_imprv_hstd_val
      t.integer :omitted_imprv_non_hstd_val
      t.integer :clt_amt
      t.integer :clt_allocation_factor
      t.integer :dvhss_amt
      t.integer :dvhss_allocation_factor
      t.integer :homestead_group_exemption_factor
      t.integer :ex_xd_amt
      t.integer :ex_xd_allocation_factor
      t.integer :ex_xf_amt
      t.integer :ex_xf_allocation_factor
      t.integer :ex_xg_amt
      t.integer :ex_xg_allocation_factor
      t.integer :ex_xh_amt
      t.integer :ex_xh_allocation_factor
      t.integer :ex_xi_amt
      t.integer :ex_xi_allocation_factor
      t.integer :ex_xj_amt
      t.integer :ex_xj_allocation_factor
      t.integer :ex_xl_amt
      t.integer :ex_xl_allocation_factor
      t.integer :ex_xm_amt
      t.integer :ex_xm_allocation_factor
      t.integer :ex_xn_amt
      t.integer :ex_xn_allocation_factor
      t.integer :ex_xo_amt
      t.integer :ex_xo_allocation_factor
      t.integer :ex_xp_amt
      t.integer :ex_xp_allocation_factor
      t.integer :ex_xq_amt
      t.integer :ex_xq_allocation_factor
      t.integer :ex_xr_amt
      t.integer :ex_xr_allocation_factor
      t.integer :ex_xs_amt
      t.integer :ex_xs_allocation_factor
      t.integer :ex_xt_amt
      t.integer :ex_xt_allocation_factor
      t.integer :ex_xu_amt
      t.integer :ex_xu_allocation_factor
      t.integer :ex_xv_amt
      t.integer :ex_xv_allocation_factor
      t.integer :ex_xa_amt
      t.integer :ex_xa_allocation_factor
      t.integer :lve_allocation_factor
      t.integer :ppv_amt
      t.integer :ppv_allocation_factor
      t.integer :dvch_amt
      t.integer :dvch_allocation_factor
      t.integer :dvchs_amt
      t.integer :dvchs_allocation_factor
      t.integer :masss_amt
      t.integer :masss_allocation_factor
      t.integer :pp_late_interstate_allocation_val
      t.integer :frss_amt
      t.integer :frss_allocation_factor
      t.integer :abmno_amt
      t.integer :abmno_allocation_factor
      t.integer :dis_amt
      t.integer :dis_allocation_factor

      t.timestamps
    end
  end
end
